env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - next/core-web-vitals
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2021
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-unused-vars:
    - 1
    - vars: all
      args: after-used
      ignoreRestSiblings: false
  react/jsx-uses-react:
    - off
  react/react-in-jsx-scope:
    - off
